object Modules {
    const val app = ":app"
    const val arch = ":libraries:arch"
    const val splash = ":features:splash"
    const val login = ":features:loggedout:login"
    const val profile = ":features:loggedin:profile"
    const val recipe = ":features:loggedin:recipe"
    const val listIngredients = ":features:loggedin:listingredients"
    const val listRecipe = ":features:loggedin:listrecipes"
    const val domain = ":core:common:domain"
    const val navigation = ":core:common:navigation"
    const val design = ":libraries:design"
    const val loggedNavigation =":features:loggedin:host"
    const val notLoggedNavigation =":features:loggedout:host"
}