object Versions {
    const val coroutines_version = "1.8.1"
    const val firebase_bom_version = "32.1.0"
    const val services_auth_version = "20.5.0"
    const val ad_mob_version = "23.1.0"
    const val glide_version = "4.16.0"
    const val credentials_version = "1.3.0"
    const val google_id_version = "1.1.1"
    const val kotlin_coroutines_test_version = "1.8.1"
    const val mockito_kotlin_version = "4.0.0"
    const val mockito_core_version = "4.8.0"
    const val mockito_inline_version = "4.8.0"
    const val mockk_version = "1.13.11"
    const val kotlin_test_version = "2.0.0"
}
